
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdphzoklrnleszyfkrzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcGh6b2tscm5sZXN6eWZrcnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDU5NjcsImV4cCI6MjA1OTA4MTk2N30.uvyqDfvAG5pKBjKkMi2uusiZl6V7AvmghVTdq36HndU";

// Types for the edge functions
export type LogCollectorPayload = {
  logs: Array<{
    timestamp: number;
    level: 'info' | 'warning' | 'error' | 'debug';
    source: 'frontend' | 'api' | 'routing';
    message: string;
    metadata?: Record<string, any>;
    provider?: 'aws' | 'azure' | 'gcp';
  }>;
  source: string;
  userAgent: string;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
